[tool.poetry]
name = "users_settings_server"
version = "0.1.0"
description = ""
authors = ["Kurbanov Bulat <kurbanovbul@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = ">=0.77.1"
fastapi-pagination = "^0.9.3"
alembic = "^1.7.7"
ormar = {version = ">=0.11", extras = ["postgresql"]}
uvicorn = {extras = ["standart"], version = "^0.17.6"}
httpx = "^0.22.0"
aioredis = "^2.0.1"
orjson = "^3.6.8"
prometheus-fastapi-instrumentator = "^5.8.1"
asyncpg = ">=0.25"
uvloop = "^0.16.0"
gunicorn = "^20.1.0"
sentry-sdk = "^1.5.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.vscode
  | \venv
  | alembic
)/
'''

[tool.flake8]
ignore = [
    # Whitespace before ':' ( https://www.flake8rules.com/rules/E203.html )
    "E203"
]
max-line-length=88
max-complexity = 15
select = "B,C,E,F,W,T4,B9"
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
    # The conf file is mostly autogenerated, ignore it
    "src/app/alembic/*",
    # The old directory contains Flake8 2.0
]

[tool.isort]
profile = "black"
only_sections = true
force_sort_within_sections = true
lines_after_imports = 2
lexicographical = true
sections = ["FUTURE", "STDLIB", "BASEFRAMEWORK", "FRAMEWORKEXT", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_baseframework = ["fastapi",]
known_frameworkext = ["starlette",]
src_paths = ["src"]
